version: '3.7'

services:
  node-server:
    build:
      network: host
      context: server
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./server/src:/home/node/app/src
      - ./server/nodemon.json:/home/node/app/nodemon.json
    container_name: node-server
    expose:
      - '4000'
    ports:
      - '4000:4000'
    command: npm run dev
    links:
      - mongo
    depends_on:
      - mongo
  react-client:
    build:
      network: host
      context: client
      dockerfile: Dockerfile
      target: base
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./client:/app
      - /app/node_modules
    container_name: react-client
    expose:
      - '3000'
    ports:
      - '3000:3000'
    command: yarn start
  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - mongodb:/data/db
    ports:
      - '27017:27017'
volumes:
  mongodb:
